version: '3.6'

networks:
  ship-network:
    driver: bridge

volumes:
  hexagonship-postgres-data:
    name: hexagonship-postgres-data

services:
  hexagonship-frontend:
    container_name: hexagonship-frontend
    image: ddd-ship-frontend
    build:
      dockerfile: Dockerfile
      context: ship-frontend/.
    networks:
      - ship-network
    ports:
      - "80:80"
    depends_on:
      - hexagonship-service
      - hexagonship-db

  hexagonship-service:
    container_name: hexagonship-backend
    image: ddd-ship-backend
    build:
      dockerfile: Dockerfile
      context: ship-backend/.
    environment:
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - ship-network
    ports:
      - "8080:8080"
    depends_on:
      - hexagonship-db

  hexagonship-db:
    container_name: hexagonship-db-postgres
    image: postgres:13.6
    networks:
      - ship-network
    environment:
      - "POSTGRES_DB=hexagonship"
      - "POSTGRES_USER=hexagonship_user"
      - "POSTGRES_PASSWORD=hexagonship_user"
    ports:
      - "5432:5432"
    volumes:
      - "hexagonship-postgres-data:/var/lib/postgresql/data"