version: '3.6'

networks:
  ship-network:
    driver: bridge

volumes:
  hexagonship-postgres-data:
    name: hexagonship-postgres-data

services:
  hexagonship-service:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - ship-network
    ports:
      - "8080:8080"

  hexagonship-db:
    container_name: hexagonship-db-postgres
    image: postgres:13.6
    networks:
      - ship-network
    environment:
      - "POSTGRES_DB=hexagonship"
      - "POSTGRES_USER=hexagonship_user"
      - "POSTGRES_PASSWORD=hexagonship_user"
    ports:
      - "5432:5432"
    volumes:
      - "hexagonship-postgres-data:/var/lib/postgresql/data"