version: '3.6'

volumes:
  hexagonship-postgres-data:
    name: hexagonship-postgres-data

services:
  hexagonship-db:
    container_name: hexagonship-db-postgres
    image: postgres:13.6
    environment:
      - "POSTGRES_DB=hexagonship"
      - "POSTGRES_USER=hexagonship_user"
      - "POSTGRES_PASSWORD=hexagonship_user"
    ports:
      - "5432:5432"
    volumes:
      - "hexagonship-postgres-data:/var/lib/postgresql/data"
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
