INSERT INTO cargos(id, cargo_id, cargo_name, cargo_weight) VALUES (1, gen_random_uuid(),'Ale', 2.0);
INSERT INTO cargos(id, cargo_id, cargo_name, cargo_weight) VALUES (2, gen_random_uuid(),'Chocolate', 0.8);
INSERT INTO cargos(id, cargo_id, cargo_name, cargo_weight) VALUES (3, gen_random_uuid(), 'Cinnamon', 0.9);
INSERT INTO cargos(id, cargo_id, cargo_name, cargo_weight) VALUES (4, gen_random_uuid(), 'Coffee', 1.9);
INSERT INTO cargos(id, cargo_id, cargo_name, cargo_weight) VALUES (5, gen_random_uuid(),'Fruits', 2.3);
INSERT INTO cargos(id, cargo_id, cargo_name, cargo_weight) VALUES (6, gen_random_uuid(), 'Leather', 3.1);
INSERT INTO cargos(id, cargo_id, cargo_name, cargo_weight) VALUES (7, gen_random_uuid(), 'Paprika', 1);
INSERT INTO cargos(id, cargo_id, cargo_name, cargo_weight) VALUES (8, gen_random_uuid(), 'Planks', 3.3);
INSERT INTO cargos(id, cargo_id, cargo_name, cargo_weight) VALUES (9, gen_random_uuid(),'Rum', 5.5);
INSERT INTO cargos(id, cargo_id, cargo_name, cargo_weight) VALUES (10,gen_random_uuid(),'Silk', 2);
INSERT INTO cargos(id, cargo_id, cargo_name, cargo_weight) VALUES (11,gen_random_uuid(), 'Sugar', 0.7);
INSERT INTO cargos(id, cargo_id, cargo_name, cargo_weight) VALUES (12,gen_random_uuid(), 'Tobacco', 3);
INSERT INTO cargos(id, cargo_id, cargo_name, cargo_weight) VALUES (13,gen_random_uuid(),'Wheat', 2.7);
INSERT INTO cargos(id, cargo_id, cargo_name, cargo_weight) VALUES (14,gen_random_uuid(), 'Wine',3.3);
