spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hexagonship
    username: hexagonship_user
    password: hexagonship_user
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false

minio:
  url: http://localhost:9000