spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:/home/maurizio/h2/hexagon-ship
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  h2:
    console:
      enabled: true