spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://hexagonship-db-postgres:5432/hexagonship
    username: hexagonship_user
    password: hexagonship_user
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect