spring:
  datasource:
    url: jdbc:postgresql://hexagonship-db-postgres:5432/hexagonship
    username: hexagonship_user
    password: hexagonship_user
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration

minio:
  url: http://hexagonship-minio:9000
  access:
    name: hexagonminio
    secret: hexagonminio
  bucket:
    name: catains
