apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: ddd-ship
type: Opaque
data:
  POSTGRES_DB: aGV4YWdvbnNoaXA=
  POSTGRES_USER: aGV4YWdvbnNoaXBfdXNlcg==
  POSTGRES_PASSWORD: aGV4YWdvbnNoaXBfdXNlcg==
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: ddd-ship
type: Opaque
data:
  MINIO_ROOT_USER: aGV4YWdvbm1pbmlv
  MINIO_ROOT_PASSWORD: aGV4YWdvbm1pbmlv
