INSERT INTO quotes(id, quote) Values(1,'There is nothing more enticing, disenchanting, and enslaving than the life at sea.' );
INSERT INTO quotes(id, quote) Values(2,'I wanted freedom, open air, and adventure. I found it on the sea.' );
INSERT INTO quotes(id, quote) Values(3,'Smell the sea and feel the sky. Let your soul and spirit fly.' );
INSERT INTO quotes(id, quote) Values(4,'It is not that life ashore is distasteful to me. But life at sea is better.' );
INSERT INTO quotes(id, quote) Values(5,'The days pass happily with me wherever my ship sails.' );
INSERT INTO quotes(id, quote) Values(6,'Now…bring me that horizon.' );
INSERT INTO quotes(id, quote) Values(7,'The goal is not to sail the boat, but rather to help the boat sail herself.' );
INSERT INTO quotes(id, quote) Values(8,'A ship in the harbor is safe, but that’s not what ships are built for.' );
INSERT INTO quotes(id, quote) Values(9,'Not all treasure is silver and gold, mate.' );
INSERT INTO quotes(id, quote) Values(10,'If one does not know to which port one is sailing, no wind is favorable.' );
INSERT INTO quotes(id, quote) Values(11,'Live in the sunshine, swim the sea, drink the wild air.' );
INSERT INTO quotes(id, quote) Values(12,'Smooth seas do not make skillful sailors.' );
INSERT INTO quotes(id, quote) Values(13,'Any fool can carry on, but a wise man knows how to shorten sail in time.' );
INSERT INTO quotes(id, quote) Values(14,'There are some things you learn best in calm, and some in storm.' );
