-- A ship may now carry the same Cargo more than once (STORY-022), so the composite key V12 gave
-- this table on (ship_id, cargo_id) no longer holds: a surrogate id replaces it.
--
-- The entity mapping stays a plain @ManyToMany bag with no id property on the join table, so
-- Hibernate's generated INSERT INTO ships_cargos (...) names only (ship_id, cargo_id). Without a
-- database-side default, the new id column's NOT NULL constraint would fail every load.
ALTER TABLE ships_cargos ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE ships_cargos DROP CONSTRAINT pk_ships_cargos;

ALTER TABLE ships_cargos ADD CONSTRAINT pk_ships_cargos PRIMARY KEY (id);
