name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    name: Build and push Hexagonship Backend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push production image
      uses: docker/build-push-action@v6
      with:
        context: ./ship-backend
        file: ship-backend/Dockerfile
        tags: ${{ secrets.DOCKERHUB_USER }}/${{ secrets. DOCKERHUB_PROJECT_NAME}}:latest
        push: true
        platforms: linux/amd64,linux/arm64
