name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    name: Build and push Hexagonship Backend
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    - name: Build Docker Image
      run: docker build ./ship-backend --file ship-backend/Dockerfile --tag ${{ secrets.DOCKERHUB_USER }}/${{ secrets. DOCKERHUB_PROJECT_NAME}}:latest
      
    - name: Docker Push
      run: docker push ${{ secrets.DOCKERHUB_USER }}/${{ secrets. DOCKERHUB_PROJECT_NAME}}:latest
